#pragma once

#define COMBO_VARIABLE_LEN
#undef COMBO_TERM
#define COMBO_TERM 30

#define PERMISSIVE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS
#define TAPPPING_TERM 100
#define FP_SUPER_TAB_TIMEOUT 500
#define ONESHOT_TIMEOUT 500

// #ifdef RGBLIGHT_LIMIT_VAL
// #undef RGBLIGHT_LIMIT_VAL
// #endif
// #define RGBLIGHT_LIMIT_VAL 120
#define RGBLIGHT_LAYERS_RETAIN_VAL
#define FP_STARTUP_ANIMATION_DISABLE
#define FP_LAYER_LIGHTING_HUE_1 HSV_CYAN
#define FP_LAYER_LIGHTING_MODE_1 RGBLIGHT_MODE_BREATHING1
#define FP_LAYER_LIGHTING_HUE_2 FP_HSV_LAVENDER
#define FP_LAYER_LIGHTING_MODE_2 RGBLIGHT_MODE_BREATHING1
#define FP_LAYER_LIGHTING_HUE_3 FP_HSV_MELON
#define FP_LAYER_LIGHTING_MODE_3 RGBLIGHT_MODE_BREATHING1
#define FP_LAYER_LIGHTING_CAPS_LOCK_MODE RGBLIGHT_MODE_KNIGHT1