#pragma once

#define COMBO_VARIABLE_LEN
#undef COMBO_TERM
#define COMBO_TERM 30

#define PERMISSIVE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS
#define TAPPPING_TERM 150
#define FP_SUPER_TAB_TIMEOUT 500
#define ONESHOT_TIMEOUT 1000